### PR TITLE
Bit of cleanup

### PR DESCRIPTION
**Pull request by firekesti**
@IrosTheBeggar you can review this commit-by-commit if you want to see what I've done. New home screenshot:

Edit: just kidding, I fixed the menu/settings icon too, new screenshot:
device-2016-09-23-185814

### CODE REVIEW

**Comment by firekesti** [comment]
Fixed the colors:

device-2016-09-23-191351

**Comment by firekesti** [comment]
device-2016-09-23-193146

**Comment by firekesti** [comment]
ok @IrosTheBeggar - this is all I'm gonna do for now!

We should replace the ListViews with RecyclerViews, probably also replace the LinkedLists, and we can likely replace the server Spinner with a RecyclerView as well if the nav drawer is mostly for selecting the current server.

**Comment by IrosTheBeggar** [comment]
@firekesti this looks good.  Just changing those was a huge improvement lol.  Thanks!

**Pull request merged**
